#!/usr/bin/env python3
"""Render the security catalogue from its JSON source, or check the committed view."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def link(path, label=None):
    return f'[{label or path}](../../{path})'


def render(catalogue):
    lines = [
        '# Attack-vector catalogue', '',
        '<!-- Generated by scripts/render_vectors.py from vectors.json. Do not edit by hand. -->', '',
        'These rows describe review questions and bounded experiments. Static observations',
        'set review priority; they do not establish vulnerabilities. An example marked as',
        'a control removes only the stated mechanism. Neither a clean lint nor an unsuccessful',
        'hunt proves safety. No row assesses a live deployment as exploitable.', '',
        'Scenario suites reduce one script under supplied synthetic context and report',
        '`nodeValidated: false`. Only fresh full validation plus a declared, violated property',
        'can produce a `confirmed-violation`, conditional on its supplied premises.', '',
        'The instruments listed are available now: the five registered lints, the bounded',
        'spend hunt, the bounded drain hunt, supplied scenarios, full node validation, and',
        'manual review. Listing an instrument does not mean it covers every mechanism in a row.',
        'The notes state those limits; future roadmap units are not current instruments.', '',
        'Each new pair has `contract.test.json` for the vulnerable source and `fixed.test.json`',
        'for its control because a suite compiles one contract. The contexts match across',
        'the pair (with `$self` resolved to the contract under test); the adversarial cases',
        'accept versus refuse, and the intended case accepts in both. These are teaching',
        'fixtures, not deployment recipes or complete transaction-validity witnesses.', '',
        f'{len(catalogue["vectors"])} vectors in {len(catalogue["classes"])} classes. '
        f'{sum(any(i != "manual" for i in v["instrument"]) for v in catalogue["vectors"])} '
        'rows name at least one forge instrument; this is availability, not measured coverage.', '',
    ]
    for number, cls in enumerate(catalogue['classes'], 1):
        lines.extend([f'## {number}. {cls["title"]}', ''])
        for row in catalogue['vectors']:
            if row['class'] != cls['id']:
                continue
            lines.extend([f'### {row["title"]}', '', f'ID: `{row["id"]}`.', '',
                          row['mechanism'], '',
                          'Instruments: ' + ', '.join(f'`{i}`' for i in row['instrument']) + '.', ''])
            for role, label in [('exhibits', 'Exhibits the mechanism'), ('control', 'Control')]:
                for example in row['examples'][role]:
                    pointer = f' (JSON pointer `{example["pointer"]}`)' if 'pointer' in example else ''
                    lines.extend([f'- {label}: {link(example["path"])}{pointer}. {example["notes"]}'])
            lines.append('')
            if 'suites' in row:
                lines.extend(['Suites: ' + ', '.join(link(p) for p in row['suites'].values()) + '.', ''])
            if row.get('incident'):
                lines.extend(['Incident: ' + row['incident'], ''])
            lines.extend([row['notes'], ''])
    return '\n'.join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if VECTORS.md needs regeneration')
    args = parser.parse_args(argv)
    catalogue = json.loads((ROOT / 'docs/security/vectors.json').read_text(encoding='utf-8'))
    output = ROOT / 'docs/security/VECTORS.md'
    expected = render(catalogue)
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != expected:
            print('VECTORS.md is stale; run python3 scripts/render_vectors.py', file=sys.stderr)
            return 1
        print('VECTORS.md is up to date')
    else:
        output.write_text(expected, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
